-- return {
--     "craftzdog/solarized-osaka.nvim",
--     lazy = false,
--     priority = 1000,
--     config = function()
--         require("solarized-osaka").setup({
--             -- your configuration comes here
--             -- or leave it empty to use the default settings
--             transparent = true,     -- Enable this to disable setting the background color
--             terminal_colors = true, -- Configure the colors used when opening a `:terminal` in [Neovim](https://github.com/neovim/neovim)
--             styles = {
--                 -- Style to be applied to different syntax groups
--                 -- Value is any valid attr-list value for `:help nvim_set_hl`
--                 comments = { italic = true },
--                 keywords = { italic = true },
--                 functions = {},
--                 variables = {},
--                 -- Background styles. Can be "dark", "transparent" or "normal"
--                 sidebars = "dark",            -- style for sidebars, see below
--                 floats = "dark",              -- style for floating windows
--             },
--             sidebars = { "qf", "help" },      -- Set a darker background on sidebar-like windows. For example: `["qf", "vista_kind", "terminal", "packer"]`
--             day_brightness = 0.3,             -- Adjusts the brightness of the colors of the **Day** style. Number between 0 and 1, from dull to vibrant colors
--             hide_inactive_statusline = false, -- Enabling this option, will hide inactive statuslines and replace them with a thin border instead. Should work with the standard **StatusLine** and **LuaLine**.
--             dim_inactive = true,              -- dims inactive windows
--             lualine_bold = true,              -- When `true`, section headers in the lualine theme will be bold
--             on_colors = function(colors)
--                 colors.border = "#565f89"
--             end,
--         })
--         vim.cmd [[colorscheme solarized-osaka]]
--     end
-- }
-- return {
--     'Verf/deepwhite.nvim',
--     lazy = false,
--     priority = 1000,
--     config = function()
--         vim.cmd [[colorscheme deepwhite]]
--     end,
-- }
-- return {
--     "ellisonleao/gruvbox.nvim",
--     priority = 1000,
--     config = function()
--         -- Default options:
--         require("gruvbox").setup({
--             terminal_colors = false, -- add neovim terminal colors
--             undercurl = true,
--             underline = true,
--             bold = true,
--             italic = {
--                 strings = true,
--                 emphasis = true,
--                 comments = true,
--                 operators = false,
--                 folds = true,
--             },
--             strikethrough = true,
--             invert_selection = false,
--             invert_signs = false,
--             invert_tabline = false,
--             invert_intend_guides = false,
--             inverse = false,   -- invert background for search, diffs, statuslines and errors
--             contrast = "hard", -- can be "hard", "soft" or empty string
--             overrides = {
--                 WinBar = { bg = '' },
--                 Visual = { bg = '#37404e' },
--                 ColorColumn = { bg = '#1e2021' },
--                 IncSearch = { bg = '' },
--                 Tabline = { bg = '' }
--             },
--             dim_inactive = false,
--             transparent_mode = false,
--         })
--         vim.cmd("set background=dark")
--         vim.cmd("colorscheme gruvbox")
--     end
-- }
-- return {
--     "zootedb0t/citruszest.nvim",
--     lazy = false,
--     priority = 1000,
--     config = function()
--         require("citruszest").setup({
--             option = {
--                 transparent = false, -- Enable/Disable transparency
--                 italic = true,
--                 bold = true,
--             },
--             -- Override default highlight style in this table
--             -- E.g If you want to override `Constant` highlight style
--             style = {
--                 -- This will change Constant foreground color and make it bold.
--                 Constant = { fg = "#FFFFFF", bold = true },
--                 Comment = { italic = true },
--                 Function = { bold = true }
--             },
--         })
--         vim.cmd('colorscheme citruszest')
--     end
-- }
return {
    "EdenEast/nightfox.nvim",
    lazy = false,
    priority = 1000,
    config = function()
        require('nightfox').setup({
            options = {
                transparent = true,
            },
            styles = {               -- Style to be applied to different syntax groups
                comments = "italic", -- Value is any valid attr-list value `:help attr-list`
                keywords = "bold",
                types = "italic,bold",
            },
        })
        vim.cmd("colorscheme terafox")
    end

}
-- return {
--     'navarasu/onedark.nvim',
--     lazy = false,
--     priority = 1000,
--     config = function()
--         -- Lua
--         require('onedark').setup {
--             -- Main options --
--             style = 'darker',             -- Default theme style. Choose between 'dark', 'darker', 'cool', 'deep', 'warm', 'warmer' and 'light'
--             transparent = true,           -- Show/hide background
--             term_colors = true,           -- Change terminal color as per the selected theme style
--             ending_tildes = false,        -- Show the end-of-buffer tildes. By default they are hidden
--             cmp_itemkind_reverse = false, -- reverse item kind highlights in cmp menu
--
--             -- toggle theme style ---
--             toggle_style_key = nil,                                                              -- keybind to toggle theme style. Leave it nil to disable it, or set it to a string, for example "<leader>ts"
--             toggle_style_list = { 'dark', 'darker', 'cool', 'deep', 'warm', 'warmer', 'light' }, -- List of styles to toggle between
--
--             -- Change code style ---
--             -- Options are italic, bold, underline, none
--             -- You can configure multiple style with comma separated, For e.g., keywords = 'italic,bold'
--             code_style = {
--                 comments = 'italic',
--                 keywords = 'none',
--                 functions = 'bold',
--                 strings = 'italic',
--                 variables = 'none'
--             },
--
--             -- Lualine options --
--             lualine = {
--                 transparent = true, -- lualine center bar transparency
--             },
--
--             -- Custom Highlights --
--             colors = {},     -- Override default colors
--             highlights = {}, -- Override highlight groups
--
--             -- Plugins Config --
--             diagnostics = {
--                 darker = true,     -- darker colors for diagnostic
--                 undercurl = true,  -- use undercurl instead of underline for diagnostics
--                 background = true, -- use background color for virtual text
--             },
--         }
--         require('onedark').load()
--         vim.cmd('colorscheme onedark')
--     end
--
-- }
-- return {
--     'projekt0n/github-nvim-theme',
--     lazy = false,    -- make sure we load this during startup if it is your main colorscheme
--     priority = 1000, -- make sure to load this before all the other start plugins
--     config = function()
--         require('github-theme').setup({
--             options = {
--                 transparent = true,
--                 styles = {               -- Style to be applied to different syntax groups
--                     comments = 'italic', -- Value is any valid attr-list value `:help attr-list`
--                     functions = 'bold',
--                     keywords = 'bold',
--                     variables = 'NONE',
--                     conditionals = 'NONE',
--                     constants = 'bold',
--                     numbers = 'bold',
--                     operators = 'NONE',
--                     strings = 'italic,bold',
--                     types = 'NONE',
--                 },
--             },
--         })
--         vim.cmd('colorscheme github_dark_colorblind')
--     end,
-- }
